from typing import List
from pydantic import BaseModel, Field
from dotenv import load_dotenv
load_dotenv()

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq
from langchain_tavily import TavilySearch
from langgraph.prebuilt import create_react_agent
import gradio as gr

# ── Pydantic Schemas ──────────────────────────────────────────────────────────

class Source(BaseModel):
    """Schema for source of information to be used by Agent to generate a response"""
    url: str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for the response generated by the Agent after processing the search results"""
    answer: str = Field(description="The Agent's response to the query.")
    sources: List[Source] = Field(description="The list of sources used by the Agent to generate the response.")

# ── System Prompt ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """
You are a job search assistant.

STRICT RULES:
1. ONLY use information returned by the search tool
2. DO NOT use prior knowledge
3. DO NOT infer or guess missing details
4. If any field is missing, write "Not specified"
5. Every job MUST include a valid apply link from the tool results
6. If no matching jobs are found, return fewer or zero results
7. Do NOT hallucinate or fabricate any job

You must extract structured job data ONLY from tool results.
Format each job clearly with:
- Job Title
- Company
- Location
- Experience Required
- Skills Mentioned
- Apply Link
"""

# ── Query Builder ─────────────────────────────────────────────────────────────

def build_query(role_type: str, experience: str, location: str, skills: list[str]) -> str:
    role = role_type.strip()
    exp = experience.strip()
    loc = location.strip()
    skills_query = " OR ".join([f'"{skill.strip()}"' for skill in skills])

    query = f"""
    ("{role}" OR "AI Engineer" OR "ML Engineer" OR "Generative AI Engineer")
    AND ("{exp} years" OR "{exp} yrs" OR "3-5 years")
    AND ("{loc}")
    AND ({skills_query})
    AND ("job" OR "hiring" OR "opening" OR "vacancy")
    AND (site:linkedin.com/jobs OR site:naukri.com OR site:indeed.com)
    """
    return " ".join(query.split())

# ── Core Search Function ──────────────────────────────────────────────────────

def run_job_search(
    groq_api_key: str,
    tavily_api_key: str,
    role_type: str,
    experience: str,
    location: str,
    skills_input: str
):
    # ── Validate API keys ─────────────────────────────────────────────────
    if not groq_api_key.strip():
        return "⚠️ Please enter your Groq API key.", ""
    if not tavily_api_key.strip():
        return "⚠️ Please enter your Tavily API key.", ""

    # ── Validate search inputs ────────────────────────────────────────────
    if not role_type.strip():
        return "⚠️ Please enter a role type.", ""
    if not location.strip():
        return "⚠️ Please enter a location.", ""
    if not skills_input.strip():
        return "⚠️ Please enter at least one skill.", ""

    try:
        # ── Build agent fresh with user's own keys ────────────────────────
        search_tool = TavilySearch(
            max_results=5,
            search_depth="advanced",
            tavily_api_key=tavily_api_key.strip()   # user's Tavily key
        )

        llm = ChatGroq(
            model="llama-3.3-70b-versatile",
            temperature=0.0,
            api_key=groq_api_key.strip()            # user's Groq key
        )

        agent = create_react_agent(
            model=llm,
            tools=[search_tool],
            response_format=AgentResponse
        )

        # ── Build query & invoke agent ────────────────────────────────────
        skills = [s.strip() for s in skills_input.split(",") if s.strip()]
        query  = build_query(role_type, experience, location, skills)

        result = agent.invoke({
            "messages": [
                SystemMessage(content=SYSTEM_PROMPT),
                HumanMessage(content=query)
            ]
        })

        structured: AgentResponse = result["structured_response"]

        # ── Format outputs ────────────────────────────────────────────────
        answer_md = structured.answer.strip() if structured.answer.strip() else "_No matching jobs found._"

        if structured.sources:
            valid_sources = [
                src for src in structured.sources
                if src.url and src.url.lower() not in ("not specified", "")
            ]
            sources_md = "\n".join(f"- [{src.url}]({src.url})" for src in valid_sources)
            if not sources_md.strip():
                sources_md = "_No sources returned._"
        else:
            sources_md = "_No sources returned._"

        return answer_md, sources_md

    except Exception as e:
        error = str(e)
        # Give a friendlier message for common auth errors
        if "401" in error or "invalid_api_key" in error.lower() or "authentication" in error.lower():
            return "❌ Invalid API key. Please double-check your Groq or Tavily key and try again.", ""
        return f"❌ Error running agent:\n\n```\n{error}\n```", ""

# ── Gradio UI ─────────────────────────────────────────────────────────────────

CSS = """
body, .gradio-container {
    font-family: 'Georgia', 'Times New Roman', serif !important;
    background-color: #f4f1ec !important;
}
#header {
    background: #1a2742;
    border-radius: 10px;
    padding: 28px 36px 20px 36px;
    margin-bottom: 24px;
}
#header h1 {
    color: #e8d9b0 !important;
    font-size: 2rem !important;
    font-weight: 700 !important;
    letter-spacing: 0.03em;
    margin: 0 0 4px 0 !important;
}
#header p {
    color: #a8b8cc !important;
    font-size: 0.97rem !important;
    margin: 0 !important;
    font-family: 'Georgia', serif !important;
}
#keys-panel {
    background: #f0f4fa;
    border: 1px solid #b8c8e0;
    border-radius: 10px;
    padding: 20px !important;
    margin-bottom: 16px;
}
#input-panel, #output-panel {
    background: #ffffff;
    border: 1px solid #d6cfc4;
    border-radius: 10px;
    padding: 24px !important;
}
label span {
    font-family: 'Georgia', serif !important;
    font-size: 0.88rem !important;
    font-weight: 600 !important;
    color: #2c3e50 !important;
    text-transform: uppercase !important;
    letter-spacing: 0.07em !important;
}
input[type=text], input[type=password], textarea, .gr-input, .gr-box {
    border: 1px solid #c8bfb2 !important;
    border-radius: 6px !important;
    background: #faf8f5 !important;
    font-family: 'Georgia', serif !important;
    font-size: 0.95rem !important;
    color: #1a2742 !important;
}
input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color: #1a2742 !important;
    box-shadow: 0 0 0 2px rgba(26,39,66,0.12) !important;
}
#search-btn {
    background: #1a2742 !important;
    color: #e8d9b0 !important;
    border: none !important;
    border-radius: 7px !important;
    font-family: 'Georgia', serif !important;
    font-size: 1rem !important;
    font-weight: 600 !important;
    letter-spacing: 0.05em !important;
    padding: 12px 0 !important;
    transition: background 0.2s ease, transform 0.1s ease !important;
}
#search-btn:hover {
    background: #243558 !important;
    transform: translateY(-1px) !important;
}
#results-box, #sources-box {
    background: #faf8f5 !important;
    border: 1px solid #d6cfc4 !important;
    border-radius: 8px !important;
    font-family: 'Georgia', serif !important;
    font-size: 0.95rem !important;
    color: #1a2742 !important;
    padding: 16px !important;
    min-height: 80px;
}
.section-title {
    font-family: 'Georgia', serif !important;
    font-size: 0.8rem !important;
    font-weight: 700 !important;
    color: #7a6e60 !important;
    text-transform: uppercase !important;
    letter-spacing: 0.1em !important;
    margin-bottom: 8px !important;
}
.key-note {
    font-size: 0.78rem !important;
    color: #5a7a9a !important;
    font-family: 'Georgia', serif !important;
    margin-top: 6px !important;
}
#footer {
    text-align: center;
    color: #9e9488;
    font-size: 0.8rem;
    margin-top: 20px;
    font-family: 'Georgia', serif;
}
"""

with gr.Blocks(title="AI Job Search Agent") as demo:

    # ── Header ────────────────────────────────────────────────────────────────
    gr.HTML("""
    <div id="header">
        <h1>⚙ AI Job Search Agent</h1>
        <p>Powered by LangGraph · Groq · Tavily — finds real AI/ML job listings across LinkedIn, Naukri & Indeed</p>
    </div>
    """)

    # ── API Keys Panel ────────────────────────────────────────────────────────
    with gr.Group(elem_id="keys-panel"):
        gr.HTML('<div class="section-title">🔑 Your API Keys</div>')
        gr.HTML('<div class="key-note">Your keys are used only for your search and are never stored or logged.</div>')

        with gr.Row():
            groq_key_input = gr.Textbox(
                label="Groq API Key",
                placeholder="gsk_...",
                type="password",   # hides the key like a password field
                scale=1
            )
            tavily_key_input = gr.Textbox(
                label="Tavily API Key",
                placeholder="tvly-...",
                type="password",   # hides the key like a password field
                scale=1
            )

        gr.HTML("""
        <div class="key-note">
            Get your free keys →
            <a href="https://console.groq.com" target="_blank">Groq Console</a> &nbsp;|&nbsp;
            <a href="https://app.tavily.com" target="_blank">Tavily Dashboard</a>
        </div>
        """)

    # ── Search + Results ──────────────────────────────────────────────────────
    with gr.Row(equal_height=False):

        # ── Left: Input Panel ─────────────────────────────────────────────
        with gr.Column(scale=1, elem_id="input-panel"):
            gr.HTML('<div class="section-title">Search Criteria</div>')

            role_input = gr.Textbox(
                label="Role Type",
                placeholder="e.g. Generative AI Engineer",
                value="AI / ML / Generative AI Engineer"
            )
            experience_input = gr.Textbox(
                label="Experience (years)",
                placeholder="e.g. 3 to 5",
                value="3 to 5"
            )
            location_input = gr.Textbox(
                label="Location",
                placeholder="e.g. Bengaluru, India",
                value="Bengaluru, India"
            )
            skills_input = gr.Textbox(
                label="Skills (comma-separated)",
                placeholder="e.g. RAG, LLM, LangChain, LangGraph",
                value="RAG, LLM, LangChain, LangGraph",
                lines=2
            )

            search_btn = gr.Button("🔍  Search Jobs", elem_id="search-btn")

        # ── Right: Output Panel ───────────────────────────────────────────
        with gr.Column(scale=2, elem_id="output-panel"):
            gr.HTML('<div class="section-title">Job Results</div>')
            results_output = gr.Markdown(
                value="_Results will appear here after search..._",
                elem_id="results-box"
            )

            gr.HTML('<div class="section-title" style="margin-top:20px;">Sources</div>')
            sources_output = gr.Markdown(
                value="_Source links will appear here..._",
                elem_id="sources-box"
            )

    # ── Footer ────────────────────────────────────────────────────────────────
    gr.HTML('<div id="footer">Results are fetched live from the web. Always verify job details on the source platform.</div>')

    # ── Button Click Event ────────────────────────────────────────────────────
    search_btn.click(
        fn=run_job_search,
        inputs=[
            groq_key_input,
            tavily_key_input,
            role_input,
            experience_input,
            location_input,
            skills_input
        ],
        outputs=[results_output, sources_output],
        show_progress="full"
    )

# ── Entry Point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    demo.launch(css = CSS , share=True)  # share=True is now safe — users bring their own keys
