from typing import List
from unittest import result #to specify the type of the list of matched skills in the job search results
from pydantic import BaseModel,Field #to create a model for the job search results with fields for job title, company name, location, experience required, mandatory skills matched and apply link
from dotenv import load_dotenv
load_dotenv()
from langchain.agents import create_agent #to create agent
from langchain_core.tools import tool #to create tools for agent
from langchain_core.messages import HumanMessage  #to invoke agent through human message
from langchain_groq import ChatGroq #to use groq model in agent
from tavily import TavilyClient #to use tavily search function in agent

tavily = TavilyClient() #creating an instance of TavilyClient to use its search function

@tool
def search(query: str) -> str:
    """Tool that searches over the internet
    Args:
        query (str): The search query
    Returns:
        The search results
    """
    print("Searching the web for:", query)
    return tavily.search(query = query) #using tavily search function to get search results

class Source(BaseModel):
    """Schema for source of information to be used by Agent to generate a response """
    url: str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for the response generated by the Agent after processing the search results"""
    answer: str = Field(description="The Agent's response to the query.")
    sources : List[Source] = Field(description="The list of sources used by the Agent to generate the response.")


llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.2)#to use model in agent for deterministic output
tools = [search] #list of tools to be used by the agent, here we are using only one tool which is search
agent = create_agent(model=llm, tools=tools, response_format=AgentResponse) #creating the agent by passing the llm and tools to the create_agent function

def main():
    print("Hello from langchain-course!")
    query = """
You are a Job Search Agent specialized in AI/ML roles.

Search for the top 3 job listings that match ALL of the following criteria:

Role Type: AI / ML / Generative AI Engineer or equivalent
Experience: 3 to 5 years
Location: Bengaluru, India (on-site or hybrid preferred, remote considered only if explicitly Bengaluru-based)
Mandatory Skills: RAG, LLM, LangChain, LangGraph

For each job found, return the details in this exact format:

---
Job #<number>
Title: <job title>
Company: <company name>
Location: <exact location or Remote>
Experience Required: <years>
Mandatory Skills Matched: <list matched skills>
Apply Link: <url if available>
---

Rules:
- Only return jobs based in Bengaluru, India.
- Only return jobs that explicitly mention at least RAG, LLM, and LangChain or LangGraph in their requirements.
- Prefer jobs posted within the last 30 days.
- If fewer than 3 matching jobs are found, return what is available and state that fewer results were found.
- Do not hallucinate job listings. Only return results from actual search output.
"""
    result = agent.invoke({'messages' : [HumanMessage(content=query)]}) #invoking the agent with the job search query
    structured_response = result['structured_response'] #getting the structured response generated by the agent
    print("\nFinal Response:\n", structured_response.answer)
    print("\nSources:")
    for src in structured_response.sources:
        print("-", src.url)


if __name__ == "__main__":
    main()

